package:
  name: pyugend
  version: "0.1.8"

source:
   git_url: https://github.com/university-gender-evolution/py-university-gender-dynamics-pkg.git

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - cookiecutter = cookiecutter:main
    #
    # Would create an entry point called cookiecutter that calls cookiecutter.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python


  run:
    - python
    - numpy
    - pandas
    - docopt
    - matplotlib

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/audreyr/cookiecutter
  license: BSD License
  summary: 'A command-line utility that creates projects from project templates, e.g. creating a Python package project from a Python package project template.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
